In [1]:
import sys

In [3]:
sys.version

'3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]'

In [4]:
sys.platform

'win32'

In [5]:
fl = [1,2,3,4,5]

In [6]:
fl.reverse()

In [7]:
fl

[5, 4, 3, 2, 1]

In [9]:
fl.insert(6,6)

In [10]:
fl

[5, 4, 3, 2, 1, 6]

In [11]:
fl.append(7)

In [12]:
fl

[5, 4, 3, 2, 1, 6, 7]

In [13]:
fl.pop(2)

3

In [14]:
fl

[5, 4, 2, 1, 6, 7]

In [15]:
set(fl)

{1, 2, 4, 5, 6, 7}

In [16]:
# set -> ordered list!

In [17]:
set1 = set(fl)

In [19]:
fl.append(8)

In [20]:
set1

{1, 2, 4, 5, 6, 7}

In [21]:
set2 = set(fl)

In [22]:
comb = set1 | set2

In [23]:
comb

{1, 2, 4, 5, 6, 7, 8}

In [24]:
intersection = set1 & set2

In [25]:
intersection

{1, 2, 4, 5, 6, 7}

In [26]:
import numpy as np

In [27]:
arr1 = np.array(fl)

In [28]:
arr1

array([5, 4, 2, 1, 6, 7, 8, 8])

In [32]:
arr1 = arr1.reshape(2,4)

In [34]:
arr1

array([[5, 4, 2, 1],
       [6, 7, 8, 8]])

In [35]:
arr1.ndim

2

In [36]:
arr1.size

8

In [37]:
arr2 = np.array([[1,1,2],[2,2,3]])

In [38]:
arr2

array([[1, 1, 2],
       [2, 2, 3]])

In [39]:
arr1.shape, arr2.shape

((2, 4), (2, 3))

In [49]:
arr3d = np.array([[[1,0],[2,0],[3,0]],[[3,0],[4,0],[7,0]],[[5,0],[6,0],[11,0]]])

In [50]:
arr3d

array([[[ 1,  0],
        [ 2,  0],
        [ 3,  0]],

       [[ 3,  0],
        [ 4,  0],
        [ 7,  0]],

       [[ 5,  0],
        [ 6,  0],
        [11,  0]]])

In [51]:
arr3d.ndim, arr3d.shape, arr3d.size

(3, (3, 3, 2), 18)

In [52]:
arr4d = np.array([[[[[1],[0]],[[2],[0]],[[3],[0]]],[[[3],[0]],[[4],[0]]],[[7],[0]],[[[5],[0]],[[6],[0]],[[11],[0]]]]])

In [53]:
arr4d

array([[list([[[1], [0]], [[2], [0]], [[3], [0]]]),
        list([[[3], [0]], [[4], [0]]]), list([[7], [0]]),
        list([[[5], [0]], [[6], [0]], [[11], [0]]])]], dtype=object)

In [54]:
arr4d.ndim, arr4d.shape, arr4d.size

(2, (1, 4), 4)

In [55]:
a = np.arange(99)

In [56]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [57]:
z = np.zeros(99)

In [58]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
e = np.empty(9)

In [61]:
e

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 2.94463125e-321, 1.13951174e-311, 0.00000000e+000,
       4.00061988e-309])

In [64]:
arr3d.ravel()

array([ 1,  0,  2,  0,  3,  0,  3,  0,  4,  0,  7,  0,  5,  0,  6,  0, 11,
        0])

In [65]:
arr1

array([[5, 4, 2, 1],
       [6, 7, 8, 8]])

In [66]:
arr2

array([[1, 1, 2],
       [2, 2, 3]])

In [69]:
np.hsplit(arr1,2)

[array([[5, 4],
        [6, 7]]), array([[2, 1],
        [8, 8]])]

In [72]:
np.vsplit(arr2,2)

[array([[1, 1, 2]]), array([[2, 2, 3]])]

In [74]:
np.hstack((arr2,arr1))

array([[1, 1, 2, 5, 4, 2, 1],
       [2, 2, 3, 6, 7, 8, 8]])

In [75]:
import pandas as pd

In [76]:
l1 = [1,2,3,3,4,5,6,6,6,7,8,9,9,9,90,0,0]

In [77]:
s1 = pd.Series(l1)

In [78]:
s1

0      1
1      2
2      3
3      3
4      4
5      5
6      6
7      6
8      6
9      7
10     8
11     9
12     9
13     9
14    90
15     0
16     0
dtype: int64

In [99]:
pali = 'malayyalama'

In [100]:
ilap = pali[::-1]

In [101]:
pali == ilap

False

In [110]:
dic1 = {'name': s1}

In [111]:
df1 = pd.DataFrame(dic1)

In [112]:
df1

name
0      1
1      2
2      3
3      3
4      4
5      5
6      6
7      6
8      6
9      7
10     8
11     9
12     9
13     9
14    90
15     0
16     0

In [114]:
df1['name'][9]

7

In [115]:
df1.name

0      1
1      2
2      3
3      3
4      4
5      5
6      6
7      6
8      6
9      7
10     8
11     9
12     9
13     9
14    90
15     0
16     0
Name: name, dtype: int64